name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          rm -rf venv
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run linter
        run: |
          source venv/bin/activate
          flake8 .

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

      - name: Send Telegram Notification
        if: failure()
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          parse-mode: ""
          disable-web-page-preview: true
          message: |
            При прохождении пайплайна возникла ошибка
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Версия Python: ${{ matrix.python-version }}
            Автор: ${{ github.actor }}
            Посмотреть лог: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}